# Generated by Django 2.2.12 on 2020-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
