# Generated by Django 2.2.12 on 2020-04-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
