# Generated by Django 2.2.12 on 2020-04-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_control', '0003_auto_20200409_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_control.Category'),
        ),
    ]
